import 'package:flutter/material.dart';
import 'package:get/get.dart';

class LocalizationService extends Translations {
  static final locale = _getLocaleFromLanguage();
  static final fallbackLocale = Locale('en', 'US');

  static final langs = ['English', 'العربية'];
  static final locales = [Locale('en', 'US'), Locale('ar', 'SA')];

  static void changeLocale(String lang) {
    final locale = _getLocaleFromLanguage(lang);
    Get.updateLocale(locale);
  }

  static Locale _getLocaleFromLanguage([String? lang]) {
    // استخدام القيمة المدخلة أو الافتراضية من الجهاز
    final languageCode = lang ?? Get.deviceLocale?.languageCode ?? 'en';
    for (int i = 0; i < langs.length; i++) {
      if (languageCode == locales[i].languageCode) {
        return locales[i];
      }
    }
    return Get.locale ?? fallbackLocale;
  }

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Bags': 'Bags',
          'Accessories': 'Accessories',
          'Shoes': 'Shoes',
          'Jewelry': 'Jewelry',
          'Watches': 'Watches',
          'Fashion': 'Fashion',
          '1 Day': '1 Day',
          '2 Days': '2 Days',
          '3 Days': '3 Days',
          '7 Days': '7 Days',
          '14 Days': '14 Days',
          'see-all': 'See All',
          'welcome_back': 'Welcome Back,',
          'log_in': 'Log In!',
          'email': 'Email',
          'password': 'Password',
          'forget_password': 'Forget Password?',
          'dont_have_account': 'Don\'t have an account?',
          'create_here': 'Create Here',
          'search_hint': 'What are you looking for?',
          'promoted_products': 'Promoted Products',
          'promoted_products_subtitle':
              'Explore the best deals on promoted products!',
          'external_ads': 'External Ads',
          'external_ads_subtitle': 'Check out these amazing external offers!',
          'ongoing_auctions': 'Ongoing Auctions',
          'ongoing_auctions_subtitle':
              'Don\'t miss out on these ongoing auctions!',
          'no_products': 'No products available',
          'add_product': 'Add Product',
          'product_title': 'Product Title',
          'description': 'Description',
          'condition': 'Condition',
          'category': 'Category',
          'is_auction': 'Is this product an auction?',
          'product_details': 'Product Details',
          'product_not_found': 'Product not found',
          'no_description': 'No description available',
          'auction_ended': 'Auction Ended',
          'place_bid': 'Place a Bid',
          'add_to_cart': 'Add to Cart',
          'current_bid': 'Current Bid',
          'bid_amount': 'Bid Amount',
          'submit_bid': 'Submit Bid',
          'seller_cant_bid':
              'You are the owner of this product. You cannot place a bid.',
          'payment_title': 'Complete Payment',
          'payment_security':
              '⚠️ Your data is completely protected and not stored with us',
          'payment_process': 'Payment Process',
          'payment_error': 'Payment Error',
          'payment_error_desc':
              'Please check your internet connection and try again',
          'cancel_payment': 'Cancel Payment',
          'confirm_cancel_payment':
              'Are you sure you want to cancel the current payment?',
          'stay': 'Stay',
          'exit': 'Exit',
          'retry': 'Retry',
          'recent_searches': 'Recent Searches',
          'clear': 'Clear',
          'sold': 'Sold',
          'finished': 'Finished',
          'left': 'left',
          'less_than_minute': 'Less than a minute left',
          'start': 'Start',
          'update_views_failed': 'Failed to update views, please try again',
          'auction': 'Auction',
          'favorites': 'Favorites',
          'cart': 'Cart',
          'live': 'Live',
          'error': 'Error',
          'success': 'Success',
          'loading': 'Loading',
          'continue': 'Continue',
          'cancel': 'Cancel',
          'save': 'Save',
          'edit': 'Edit',
          'delete': 'Delete',
          'confirm': 'Confirm',
          'back': 'Back',
          'next': 'Next',
          'search': 'Search',
          'settings': 'Settings',
          'profile': 'Profile',
          'logout': 'Logout',
          'login': 'Login',
          'register': 'Register',
          'welcome': 'Welcome',
          'home': 'Home',
          'confirm_password': 'Confirm Password',
          'already_have_account': 'Already have an account?',
          'create_account': 'Create Account',
          'login_now': 'Login Now',
          'name': 'Name',
          'phone': 'Phone',
          'user_type': 'User Type',
          'seller': 'Seller',
          'buyer': 'Buyer',
          'products': 'Products',
          'all_products': 'All Products',
          'price': 'Price',
          'starting_price': 'Starting Price',
          'max_price': 'Maximum Price',
          'bid_now': 'Bid Now',
          'add_to_favorites': 'Add to Favorites',
          'remove_from_favorites': 'Remove from Favorites',
          'quantity': 'Quantity',
          'status': 'Status',
          'specifications': 'Specifications',
          'reviews': 'Reviews',
          'related_products': 'Related Products',
          'shopping_cart': 'Shopping Cart',
          'cart_empty': 'Your cart is empty',
          'total': 'Total',
          'proceed_to_checkout': 'Proceed to Checkout',
          'remove_item': 'Remove Item',
          'update_quantity': 'Update Quantity',
          'favorites_empty': 'No favorites yet',
          'login_to_view_favorites': 'Login to view favorites',
          'payment': 'Payment',
          'payment_method': 'Payment Method',
          'card_number': 'Card Number',
          'cardholder_name': 'Cardholder Name',
          'expiry_date': 'Expiry Date',
          'cvv': 'CVV',
          'save_card': 'Save Card',
          'pay_now': 'Pay Now',
          'payment_success': 'Payment Successful',
          'payment_failed': 'Payment Failed',
          'address': 'Address',
          'add_address': 'Add Address',
          'edit_address': 'Edit Address',
          'country': 'Country',
          'city': 'City',
          'street': 'Street',
          'building': 'Building',
          'apartment': 'Apartment',
          'zip_code': 'Zip Code',
          'save_address': 'Save Address',
          'no_addresses': 'No addresses found',
          'account_info': 'Account Info',
          'edit_profile': 'Edit Profile',
          'change_password': 'Change Password',
          'change_email': 'Change Email',
          'saved_cards': 'Saved Cards',
          'saved_addresses': 'Saved Addresses',
          'orders': 'Orders',
          'sign_out': 'Sign Out',
          'full_name': 'Full Name',
          'current_password': 'Current Password',
          'new_password': 'New Password',
          'confirm_new_password': 'Confirm New Password',
          'update': 'Update',
          'live_stream': 'Live Stream',
          'live_stream_active': 'Live stream is active',
          'no_live_stream': 'No live stream currently',
          'start_stream': 'Start Stream',
          'join_stream': 'Join Stream',
          'add_new_ad': 'Add New ad',
          'title': 'Title',
          'viewers': 'Viewers',
          'comments': 'Comments',
          'send': 'Send',
          'end_stream': 'End Stream',
          'leave_stream': 'Leave Stream',
          'notifications': 'Notifications',
          'no_notifications': 'No notifications',
          'mark_all_as_read': 'Mark all as read',
          'invalid_email': 'Invalid email',
          'invalid_password': 'Invalid password',
          'password_not_match': 'Passwords do not match',
          'required_field': 'This field is required',
          'invalid_phone': 'Invalid phone number',
          'invalid_card': 'Invalid card number',
          'invalid_date': 'Invalid date',
          'invalid_cvv': 'Invalid CVV',
          'something_went_wrong': 'Something went wrong',
          'network_error': 'Network error',
          'try_again': 'Try again',
          'no_internet': 'No internet connection',
          'login_success': 'Logged in successfully',
          'register_success': 'Registered successfully',
          'profile_updated': 'Profile updated',
          'password_changed': 'Password changed',
          'email_changed': 'Email changed',
          'address_added': 'Address added',
          'address_updated': 'Address updated',
          'address_deleted': 'Address deleted',
          'card_added': 'Card added',
          'card_deleted': 'Card deleted',
          'order_placed': 'Order placed',
          'bid_success': 'Bid placed successfully',
          'ads': 'Ads',
          'add_ad': 'Add Ad',
          'duration_days': 'Duration Days - you will pay 50\$ for each day',
          'ad_title': 'Ad Title',
          'ad_description': 'Ad Description',
          'ad_url': 'Ad URL',
          'ad_duration': 'Duration (days)',
          'ad_cost': 'Cost',
          'proceed_to_payment': 'Proceed to Payment',
          'upload_image': 'Upload Image',
          'ad_success': 'Ad created successfully',
          'tap_to_add_image': 'Tap To Add Image',
          'add_new_product': 'Add New Product',
          'New': 'New',
          'Used': 'Used',
          'select_promotion_days': 'Select Promotion Days',
          'promote_product': 'Promote Product',
          'promotion_duration': 'Promotion Duration',
          'add_ad_now': 'Add ad Now',
          'add_ad_description':
              'Add Your Ad Now and Reach Thousands of Customers',
          'start_price': 'Start Price',
          'highest_bid': 'Highest Bid',
        },
        'ar_SA': {
          'highest_bid': 'أعلى مزايدة',
          'start_price': 'السعر البدائى',
          'add_ad_description': 'أضف إعلانك الأن لتصل للآلاف من المستخدمين',
          'add_ad_now': 'أضف أعلانك الأن',
          'promotion_duration': 'مده الترويج',
          'select_promotion_days': 'إختار عدد أيام الترويج',
          'New': 'جديد',
          'Used': 'مستعمل',
          'add_new_product': 'إضافه منتج جديد',
          'Bags': 'شنط',
          'Accessories': 'إكسسوارات',
          'Shoes': 'أحذيه',
          'Jewelry': 'مجوهرات',
          'Watches': 'ساعات',
          'Fashion': 'ازياء',
          '1 Day': 'يوم',
          '2 Days': 'يومان',
          '3 Days': '3 أيام',
          '7 Days': '7 أيام',
          '14 Days': '14 يوم',
          'welcome_back': 'مرحباً بعودتك,',
          'tap_to_add_image': 'إضغط لإضافه صوره',
          'log_in': 'تسجيل الدخول!',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة المرور',
          'forget_password': 'نسيت كلمة المرور؟',
          'dont_have_account': 'ليس لديك حساب؟',
          'create_here': 'أنشئ حساب هنا',
          'search_hint': 'ما الذي تبحث عنه؟',
          'promoted_products': 'المنتجات المميزة',
          'promoted_products_subtitle':
              'اكتشف أفضل العروض على المنتجات المميزة!',
          'external_ads': 'الإعلانات الخارجية',
          'external_ads_subtitle': 'تحقق من هذه العروض المذهلة!',
          'ongoing_auctions': 'المزادات الجارية',
          'ongoing_auctions_subtitle': 'لا تفوت هذه المزادات الجارية!',
          'no_products': 'لا توجد منتجات متاحة',
          'add_product': 'إضافة منتج',
          'product_title': 'عنوان المنتج',
          'description': 'الوصف',
          'condition': 'الحالة',
          'category': 'الفئة',
          'is_auction': 'هل هذا المنتج مزاد؟',
          'product_details': 'تفاصيل المنتج',
          'duration_days': 'المده باليوم - كل يوم سيكلفك 50\$',
          'product_not_found': 'المنتج غير موجود',
          'no_description': 'لا يوجد وصف متاح',
          'auction_ended': 'انتهى المزاد',
          'place_bid': 'تقديم عرض',
          'add_to_cart': 'إضافة إلى السلة',
          'title': 'العنوان',
          'current_bid': 'العرض الحالي',
          'bid_amount': 'مبلغ العرض',
          'submit_bid': 'تقديم العرض',
          'seller_cant_bid': 'أنت مالك هذا المنتج. لا يمكنك تقديم عرض.',
          'payment_title': 'إتمام الدفع',
          'payment_security': '⚠️ بياناتك محمية تماماً ولا يتم تخزينها لدينا',
          'payment_process': 'عملية الدفع',
          'payment_error': 'خطأ في الدفع',
          'payment_error_desc':
              'الرجاء التحقق من اتصال الإنترنت والمحاولة مرة أخرى',
          'cancel_payment': 'إلغاء عملية الدفع',
          'confirm_cancel_payment':
              'هل أنت متأكد أنك تريد إلغاء عملية الدفع الحالية؟',
          'stay': 'البقاء',
          'exit': 'خروج',
          'retry': 'إعادة المحاولة',
          'recent_searches': 'عمليات البحث الأخيرة',
          'clear': 'مسح',
          'sold': 'تم البيع',
          'finished': 'منتهي',
          'left': 'متبقي',
          'less_than_minute': 'أقل من دقيقة متبقية',
          'start': 'بداية',
          'update_views_failed': 'فشل تحديث المشاهدات، يرجى المحاولة مرة أخرى',
          'auction': 'مزاد',
          'favorites': 'المفضلة',
          'cart': 'السلة',
          'live': 'بث مباشر',
          'error': 'خطأ',
          'success': 'نجاح',
          'loading': 'جاري التحميل',
          'continue': 'متابعة',
          'cancel': 'إلغاء',
          'save': 'حفظ',
          'edit': 'تعديل',
          'add_new_ad': 'أضف إعلان جديد',
          'delete': 'حذف',
          'confirm': 'تأكيد',
          'back': 'رجوع',
          'see-all': 'عرض المزيد',
          'next': 'التالي',
          'search': 'بحث',
          'settings': 'الإعدادات',
          'profile': 'الملف الشخصي',
          'logout': 'تسجيل الخروج',
          'login': 'تسجيل الدخول',
          'register': 'تسجيل',
          'welcome': 'مرحباً',
          'home': 'الرئيسية',
          'confirm_password': 'تأكيد كلمة المرور',
          'already_have_account': 'لديك حساب بالفعل؟',
          'create_account': 'إنشاء حساب',
          'login_now': 'سجل الدخول الآن',
          'name': 'الاسم',
          'phone': 'الهاتف',
          'user_type': 'نوع المستخدم',
          'seller': 'بائع',
          'buyer': 'مشتري',
          'products': 'المنتجات',
          'all_products': 'جميع المنتجات',
          'price': 'السعر',
          'starting_price': 'السعر الابتدائي',
          'max_price': 'السعر الأقصى',
          'bid_now': 'المزايدة الآن',
          'add_to_favorites': 'إضافة إلى المفضلة',
          'remove_from_favorites': 'إزالة من المفضلة',
          'quantity': 'الكمية',
          'status': 'الحالة',
          'specifications': 'المواصفات',
          'reviews': 'التقييمات',
          'related_products': 'منتجات ذات صلة',
          'shopping_cart': 'سلة التسوق',
          'cart_empty': 'سلة التسوق فارغة',
          'total': 'الإجمالي',
          'proceed_to_checkout': 'إتمام الشراء',
          'remove_item': 'إزالة العنصر',
          'update_quantity': 'تحديث الكمية',
          'favorites_empty': 'لا توجد عناصر في المفضلة',
          'login_to_view_favorites': 'سجل الدخول لعرض المفضلة',
          'payment': 'الدفع',
          'payment_method': 'طريقة الدفع',
          'card_number': 'رقم البطاقة',
          'cardholder_name': 'اسم حامل البطاقة',
          'expiry_date': 'تاريخ الانتهاء',
          'cvv': 'CVV',
          'save_card': 'حفظ البطاقة',
          'pay_now': 'ادفع الآن',
          'payment_success': 'تم الدفع بنجاح',
          'payment_failed': 'فشل الدفع',
          'address': 'العنوان',
          'add_address': 'إضافة عنوان',
          'edit_address': 'تعديل العنوان',
          'country': 'الدولة',
          'city': 'المدينة',
          'street': 'الشارع',
          'building': 'المبنى',
          'apartment': 'الشقة',
          'zip_code': 'الرمز البريدي',
          'save_address': 'حفظ العنوان',
          'no_addresses': 'لا توجد عناوين',
          'account_info': 'معلومات الحساب',
          'edit_profile': 'تعديل الملف الشخصي',
          'change_password': 'تغيير كلمة المرور',
          'change_email': 'تغيير البريد الإلكتروني',
          'saved_cards': 'البطاقات المحفوظة',
          'saved_addresses': 'العناوين المحفوظة',
          'orders': 'الطلبات',
          'sign_out': 'تسجيل الخروج',
          'full_name': 'الاسم الكامل',
          'current_password': 'كلمة المرور الحالية',
          'new_password': 'كلمة المرور الجديدة',
          'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
          'update': 'تحديث',
          'live_stream': 'البث المباشر',
          'live_stream_active': 'البث المباشر نشط',
          'no_live_stream': 'لا يوجد بث مباشر حالياً',
          'start_stream': 'بدء البث',
          'join_stream': 'الانضمام للبث',
          'viewers': 'المشاهدين',
          'comments': 'التعليقات',
          'send': 'إرسال',
          'end_stream': 'إنهاء البث',
          'leave_stream': 'مغادرة البث',
          'notifications': 'الإشعارات',
          'no_notifications': 'لا توجد إشعارات',
          'mark_all_as_read': 'تعليم الكل كمقروء',
          'invalid_email': 'بريد إلكتروني غير صحيح',
          'invalid_password': 'كلمة مرور غير صحيحة',
          'password_not_match': 'كلمة المرور غير متطابقة',
          'required_field': 'هذا الحقل مطلوب',
          'invalid_phone': 'رقم هاتف غير صحيح',
          'invalid_card': 'رقم بطاقة غير صحيح',
          'invalid_date': 'تاريخ غير صحيح',
          'invalid_cvv': 'CVV غير صحيح',
          'something_went_wrong': 'حدث خطأ ما',
          'network_error': 'خطأ في الشبكة',
          'try_again': 'حاول مرة أخرى',
          'no_internet': 'لا يوجد اتصال بالإنترنت',
          'login_success': 'تم تسجيل الدخول بنجاح',
          'register_success': 'تم التسجيل بنجاح',
          'profile_updated': 'تم تحديث الملف الشخصي',
          'password_changed': 'تم تغيير كلمة المرور',
          'email_changed': 'تم تغيير البريد الإلكتروني',
          'address_added': 'تم إضافة العنوان',
          'address_updated': 'تم تحديث العنوان',
          'address_deleted': 'تم حذف العنوان',
          'card_added': 'تم إضافة البطاقة',
          'card_deleted': 'تم حذف البطاقة',
          'order_placed': 'تم تقديم الطلب',
          'bid_success': 'تم تقديم المزايدة بنجاح',
          'ads': 'الإعلانات',
          'add_ad': 'إضافة إعلان',
          'ad_title': 'عنوان الإعلان',
          'ad_description': 'وصف الإعلان',
          'ad_url': 'رابط الإعلان',
          'ad_duration': 'المدة (أيام)',
          'ad_cost': 'التكلفة',
          'proceed_to_payment': 'المتابعة للدفع',
          'upload_image': 'رفع صورة',
          'ad_success': 'تم إنشاء الإعلان بنجاح',
        },
      };
}
