// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsy-BsaMfCitcn49I7nhNWvaMCUkuHc0',
    appId: '1:901073232536:web:f902f70ac48c9d26a0e6ed',
    messagingSenderId: '901073232536',
    projectId: 'bid-app-2bdd6',
    authDomain: 'bid-app-2bdd6.firebaseapp.com',
    storageBucket: 'bid-app-2bdd6.firebasestorage.app',
    measurementId: 'G-FEE5E956B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxN6CeZZrfbJWRQSD-AisD16tHQL209ks',
    appId: '1:901073232536:android:deaf89c24f8a3acea0e6ed',
    messagingSenderId: '901073232536',
    projectId: 'bid-app-2bdd6',
    storageBucket: 'bid-app-2bdd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-kBpdCUZQuyr8E0ol_Kb2HYjH_-pkHwo',
    appId: '1:901073232536:ios:9d576045d0317341a0e6ed',
    messagingSenderId: '901073232536',
    projectId: 'bid-app-2bdd6',
    storageBucket: 'bid-app-2bdd6.firebasestorage.app',
    iosBundleId: 'com.bidapp.hal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-kBpdCUZQuyr8E0ol_Kb2HYjH_-pkHwo',
    appId: '1:901073232536:ios:178bff4182e64a58a0e6ed',
    messagingSenderId: '901073232536',
    projectId: 'bid-app-2bdd6',
    storageBucket: 'bid-app-2bdd6.firebasestorage.app',
    iosBundleId: 'com.bidapp.hal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKsy-BsaMfCitcn49I7nhNWvaMCUkuHc0',
    appId: '1:901073232536:web:2b6e4e06e0aecb86a0e6ed',
    messagingSenderId: '901073232536',
    projectId: 'bid-app-2bdd6',
    authDomain: 'bid-app-2bdd6.firebaseapp.com',
    storageBucket: 'bid-app-2bdd6.firebasestorage.app',
    measurementId: 'G-EVZHNJL0Y7',
  );
}
