List<Map<String, String>> countryCodes = [
  {"code": "+1", "country": "United States"},
  {"code": "+20", "country": "Egypt"},
  {"code": "+44", "country": "United Kingdom"},
  {"code": "+971", "country": "United Arab Emirates"},
  {"code": "+91", "country": "India"},
  {"code": "+33", "country": "France"},
  {"code": "+49", "country": "Germany"},
  {"code": "+81", "country": "Japan"},
  {"code": "+86", "country": "China"},
  {"code": "+61", "country": "Australia"},
  {"code": "+7", "country": "Russia"},
  {"code": "+55", "country": "Brazil"},
  {"code": "+39", "country": "Italy"},
  {"code": "+34", "country": "Spain"},
  {"code": "+62", "country": "Indonesia"},
  {"code": "+90", "country": "Turkey"},
  {"code": "+82", "country": "South Korea"},
  {"code": "+966", "country": "Saudi Arabia"},
  {"code": "+234", "country": "Nigeria"},
  {"code": "+27", "country": "South Africa"},
  {"code": "+880", "country": "Bangladesh"},
  {"code": "+92", "country": "Pakistan"},
  {"code": "+52", "country": "Mexico"},
  {"code": "+31", "country": "Netherlands"},
  {"code": "+47", "country": "Norway"},
  {"code": "+46", "country": "Sweden"},
  {"code": "+41", "country": "Switzerland"},
  {"code": "+32", "country": "Belgium"},
  {"code": "+48", "country": "Poland"},
  {"code": "+45", "country": "Denmark"},
  {"code": "+351", "country": "Portugal"},
  {"code": "+30", "country": "Greece"},
  {"code": "+56", "country": "Chile"},
  {"code": "+57", "country": "Colombia"},
  {"code": "+98", "country": "Iran"},
  {"code": "+964", "country": "Iraq"},
  {"code": "+962", "country": "Jordan"},
  {"code": "+961", "country": "Lebanon"},
  {"code": "+965", "country": "Kuwait"},
  {"code": "+968", "country": "Oman"},
  {"code": "+973", "country": "Bahrain"},
  {"code": "+974", "country": "Qatar"},
  {"code": "+963", "country": "Syria"},
  {"code": "+216", "country": "Tunisia"},
  {"code": "+213", "country": "Algeria"},
  {"code": "+249", "country": "Sudan"},
  {"code": "+212", "country": "Morocco"},
  {"code": "+221", "country": "Senegal"},
  {"code": "+225", "country": "Ivory Coast"},
  {"code": "+231", "country": "Liberia"},
  {"code": "+250", "country": "Rwanda"},
  {"code": "+256", "country": "Uganda"},
  {"code": "+260", "country": "Zambia"},
  {"code": "+263", "country": "Zimbabwe"},
];
